### PR TITLE
Updated recipe and its tarball to version 0.2.2

### PR DESCRIPTION
**Pull request by mkuehbach**

### CODE REVIEW

**Comment by mkuehbach** [comment]
Hi Sarath, spotted that the current paraprobe-feedstock still uses this library in version 0.2.1 and that the tarball of that ifes lib version was pointing to the actual tarball hash of 0.0.9. Therefore, here PR to set the version for the conda-forge ifes library correctly to 0.2.2. and have the code for that version using the correct tarball starting with 88afa2ee40e39948211dfa1ed512867e652889d6d0a001e0caa268523563fe89

**Comment by srmnitc** [comment]
@mkuehbach this is my fork of the actual repo. The actual repo is updated to 0.2.1 as of now it seems.

**Comment by srmnitc** [comment]
https://github.com/conda-forge/ifes-apt-tc-data-modeling-feedstock/blob/main/recipe/meta.yaml

**Comment by srmnitc** [comment]
@mkuehbach PR for 0.2.2 is waiting currently. See [here](https://github.com/conda-forge/ifes-apt-tc-data-modeling-feedstock/pull/8). You can (and probably should) open PR directly on the main repo.

**Pull request merged**
